const hangmanWords = [
    { category: "Animals", solution: "Lion" },
    { category: "Animals", solution: "Elephant" },
    { category: "Animals", solution: "Giraffe" },
    { category: "Animals", solution: "Tiger" },
    { category: "Animals", solution: "Dolphin" },
    { category: "Countries", solution: "France" },
    { category: "Countries", solution: "Japan" },
    { category: "Countries", solution: "Brazil" },
    { category: "Countries", solution: "Australia" },
    { category: "Countries", solution: "Canada" },
    { category: "Fruits", solution: "Apple" },
    { category: "Fruits", solution: "Banana" },
    { category: "Fruits", solution: "Orange" },
    { category: "Fruits", solution: "Strawberry" },
    { category: "Fruits", solution: "Watermelon" },
    { category: "Movies", solution: "Titanic" },
    { category: "Movies", solution: "Inception" },
    { category: "Movies", solution: "Jurassic Park" },
    { category: "Movies", solution: "The Godfather" },
    { category: "Movies", solution: "Star Wars" },
    { category: "Professions", solution: "Doctor" },
    { category: "Professions", solution: "Teacher" },
    { category: "Professions", solution: "Engineer" },
    { category: "Professions", solution: "Artist" },
    { category: "Professions", solution: "Lawyer" },
    { category: "Sports", solution: "Soccer" },
    { category: "Sports", solution: "Basketball" },
    { category: "Sports", solution: "Tennis" },
    { category: "Sports", solution: "Swimming" },
    { category: "Sports", solution: "Volleyball" },
    { category: "Foods", solution: "Pizza" },
    { category: "Foods", solution: "Hamburger" },
    { category: "Foods", solution: "Sushi" },
    { category: "Foods", solution: "Pasta" },
    { category: "Foods", solution: "Salad" },
    { category: "Colors", solution: "Red" },
    { category: "Colors", solution: "Blue" },
    { category: "Colors", solution: "Green" },
    { category: "Colors", solution: "Yellow" },
    { category: "Colors", solution: "Purple" },
    { category: "Musical Instruments", solution: "Guitar" },
    { category: "Musical Instruments", solution: "Piano" },
    { category: "Musical Instruments", solution: "Violin" },
    { category: "Musical Instruments", solution: "Flute" },
    { category: "Musical Instruments", solution: "Trumpet" },
    { category: "Body Parts", solution: "Arm" },
    { category: "Body Parts", solution: "Leg" },
    { category: "Body Parts", solution: "Head" },
    { category: "Body Parts", solution: "Hand" },
    { category: "Body Parts", solution: "Foot" }
];

module.exports = hangmanWords;
